# Generated by Django 5.2 on 2025-04-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vida', models.IntegerField()),
                ('balas', models.IntegerField()),
                ('escudo', models.IntegerField()),
                ('rango', models.CharField(max_length=50)),
            ],
        ),
    ]
